# fly.toml app configuration file generated for advisor-agent
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'advisor-agent'
primary_region = 'sjc'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'advisor-agent.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
